name: Say Hello until create release be ready 
on:
  workflow_dispatch:
    inputs:
      input_var:
        description: "Say Hi!"
        required: true
  workflow_call:
    inputs:
      input_var:
        type: string
        required: true

permissions:
  contents: write

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "$input_var, World!"


