name: Kubeflow Release Workflow
on:
  workflow_dispatch:
jobs:
  # 1. Sync opendatahub:v1.9-branch with opendatahub:main
  sync-release-branch:
    uses: atheo89/kubeflow/.github/workflows/sync-branches-through-pr-2.yaml@main
    with:
      source: "main"
      target: "v1.9t"

  # 2. Add a delay for 10 minutes in order to have the images ready on quay.io
  wait-images-to-build-on-quay:
    needs: sync-release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 minutes
        run: sleep 600

  # 3. Update the notebook controllers’ image tags on release branch
  update-release-images:
    needs: wait-images-to-build-on-quay
    uses: atheo89/kubeflow/.github/workflows/notebook-controller-images-updater.yaml@main
    with:
      branch-name: "v1.9t"
      organization: "atheo89"
      generate-pr: "true"

  # 4. Capture PR number
  capture-pr-number:
    needs: update-release-images
    runs-on: ubuntu-latest
    steps:
      - name: Capture PR Number
        id: capture_pr
        run: |
          PR_NUMBER=$(gh pr list --repo https://github.com/atheo89/kubeflow.git \
            --head atheo89/v1.9t --state open --json number --jq '.[0].number')
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR created or found. Exiting."
            exit 1
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "::set-output name=pr_number::$PR_NUMBER"

  # 5. Check if PR is merged and create the release
  create-release:
    needs: capture-pr-number
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is merged
        id: check_pr
        run: |
          echo "Checking status of PR #${{ steps.capture_pr.outputs.pr_number }}"
          PR_STATUS=$(gh pr view ${{ steps.capture_pr.outputs.pr_number }} --repo https://github.com/atheo89/kubeflow.git --json merged --jq '.merged')
          if [ "$PR_STATUS" != "true" ]; then
            echo "PR is not merged. Exiting."
            exit 1
          fi
          echo "PR is merged. Proceeding."

      - name: Trigger create-release
        uses: atheo89/kubeflow/.github/workflows/hello.yaml@main
        with:
          input_var: "Geia"
