---
name: Kubeflow Release Workflow
on:
  workflow_dispatch: # Manual trigger for full control
  schedule:
    - cron: '0 0 * * *' # runs every day at midnight
jobs:
  # 1. Update the notebook controllers’ image tags on main
  update-main-imges:
    uses: atheo89/kubeflow/.github/workflows/notebook-controller-images-updater.yaml@main
    with: 
      branch-name: "main"
      organization: "atheo89"
      generate-pr: "false"

  # 2. Sync opendatahub:v1.9-branch with opendatahub:main (No PR needed)
  sync-branches:
    needs: update-main-imges
    uses: atheo89/kubeflow/.github/workflows/sync-branches-through-pr-2.yaml@main
    with:
      source: "main"
      target: "v1.9t"
  # 3. Add a delay for 10 minutes in order to have the images ready on the quay.io alternatvly (Maybe use skopeo)
  wait-images-to-build-on-quay:
    needs: sync-branches
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for x min
        run: sleep 1
  # 4. Update the notebook controllers’ image tags on release branch (PR needed to do the final tests)
  update-release-imges:
    needs: wait-images-to-build-on-quay
    uses: atheo89/kubeflow/.github/workflows/notebook-controller-images-updater.yaml@main
    with: 
      branch-name: "v1.9t"
      organization: "atheo89"
      generate-pr: "true"

