name: Kubeflow Release Pipeline
on:
  workflow_dispatch:
    inputs:
      create-new-release:
        description: "Create a new release?"
        required: true
        default: "true"
env:
  CREATE_NEW_RELEASE: ${{ inputs.create-new-release }}
  REPO_OWNER: atheo89
  REPO_NAME: kubeflow 
  BRANCH_NAME: v1.9t

jobs:
  # 1. Sync opendatahub:v1.9-branch with opendatahub:main
  sync-main-to-release-branch:
    uses: atheo89/kubeflow/.github/workflows/sync-branches-through-pr-2.yaml@main
    with:
      source: "main"
      target: "v1.9t"

  # 2. Poll for images to be available on quay.io the readiness of the images usually takes ~10 mins
  wait-images-are-ready-on-quay:
    needs: sync-main-to-release-branch
    runs-on: ubuntu-latest
    outputs:
      images_ready: ${{ steps.check-images.outputs.images_ready }}
    steps:
      - name: Poll for images availability
        id: check-images
        run: |

          echo "Sleeping for 5 minutes before starting polling..."
          sleep 10

          echo "images_ready=true" >> $GITHUB_ENV
          echo "images_ready=true" >> $GITHUB_OUTPUT

      - name: Images are ready
        if: ${{ env.images_ready == 'true' }}
        run: echo "All images are ready. Proceeding to the next step."

  # 3. Once Images are availble updates the notebook controllers’ image tags
  update-release-images:
    needs: wait-images-are-ready-on-quay
    if: ${{ needs.wait-images-are-ready-on-quay.outputs.images_ready == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Call Notebook Controller Images Updater Workflow
        uses: atheo89/kubeflow/.github/workflows/notebook-controller-images-updater.yaml@main
        with: 
          branch-name: "v1.9t"
          organization: "atheo89"
          generate-pr: "true"
        env:
          GH_TOKEN: ${{ secrets.SECRET_PAT }}

      
  # 4. Check PR merged status
  check-pr-merged:
    needs: update-release-images
    runs-on: ubuntu-latest
    outputs:
      pr_merged: ${{ steps.check.outputs.pr_merged }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if the PR is merged
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # PR to look for
          PR_TITLE="[GHA-${{ github.run_id }}]"
          # Fetch matching PRs
          PR_NUMBER=$(gh pr list --repo "$REPO_OWNER/$REPO_NAME" --state all --search "$PR_TITLE" --json number,title | jq -r '.[0].number')
          echo "PR number: $PR_NUMBER"
  
          if [ -z "$PR_NUMBER" ]; then
            echo "No matching PR found."
            exit 1
          fi
  
          # Polling loop to wait for the PR to be merged
          MAX_ATTEMPTS=30  # Maximum number of attempts
          SLEEP_DURATION=5  # Wait time between checks in seconds
  
          for (( i=1; i<=MAX_ATTEMPTS; i++ )); do
            echo "Checking if PR #$PR_NUMBER is merged (Attempt $i/$MAX_ATTEMPTS)..."
            PR_STATE=$(gh pr view --repo atheo89/kubeflow $PR_NUMBER --json mergedAt --jq '.mergedAt')
  
            if [ "$PR_STATE" = "null" ] || [ -z "$PR_STATE" ]; then
              echo "PR #$PR_NUMBER is not merged yet. Waiting..."
              sleep $SLEEP_DURATION
            else
              echo "PR #$PR_NUMBER is merged!"
              echo "pr_merged=true" >> $GITHUB_ENV
              echo "pr_merged=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
  
          echo "Timed out waiting for PR #$PR_NUMBER to be merged."
          echo "pr_merged=false" >> $GITHUB_ENV
          echo "pr_merged=false" >> $GITHUB_OUTPUT
          exit 1

  # 5. Create a release
  create-release:
    needs: [update-release-images, check-pr-merged]
    if: ${{ needs.check-pr-merged.outputs.pr_merged == 'true' && inputs.create-new-release == 'true' }}
    uses: atheo89/kubeflow/.github/workflows/create-release.yaml@main
    with:
      target_branch: "v1.9t"
