name: Kubeflow Release Workflow
on:
  workflow_dispatch:
jobs:
  # 1. Sync opendatahub:v1.9-branch with opendatahub:main
  sync-release-branch:
    uses: atheo89/kubeflow/.github/workflows/sync-branches-through-pr-2.yaml@main
    with:
      source: "main"
      target: "v1.9t"
  # 2. Add a delay for 10 minutes in order to have the images ready on the quay.io alternatvly (Maybe use skopeo)
  wait-images-to-build-on-quay:
    needs: sync-release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for x min
        run: sleep 1
  # 3. Update the notebook controllers’ image tags on release branch (PR needed to do the final tests)
  update-release-images:
    needs: wait-images-to-build-on-quay
    uses: atheo89/kubeflow/.github/workflows/notebook-controller-images-updater.yaml@main
    with: 
      branch-name: "v1.9t"
      organization: "atheo89"
      generate-pr: "true"
  # 4. Check PR merged status
  check-pr-merged:
    needs: update-release-images
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is merged
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --state open --head atheo89:v1.9t --json number --jq '.[0].number')
          if [ -z "$PR_NUMBER" ]; then
            echo "PR is already merged or doesn't exist."
            echo "pr_merged=true" >> $GITHUB_ENV
          else
            PR_STATE=$(gh pr view $PR_NUMBER --json merged --jq '.merged')
            if [ "$PR_STATE" = "true" ]; then
              echo "pr_merged=true" >> $GITHUB_ENV
            else
              echo "pr_merged=false" >> $GITHUB_ENV
            fi
          fi
  # 4. Create the release
  create-release:
    needs: update-release-images
    if: env.pr_merged == 'true'
    uses: atheo89/kubeflow/.github/workflows/hello.yaml@main
    with:
      input_var: "Geia"
