name: Kubeflow Release Workflow
on:
  workflow_dispatch:
jobs:
  # 1. Sync opendatahub:v1.9-branch with opendatahub:main
  sync-release-branch:
    uses: atheo89/kubeflow/.github/workflows/sync-branches-through-pr-2.yaml@main
    with:
      source: "main"
      target: "v1.9t"
  # 2. Add a delay for 10 minutes in order to have the images ready on the quay.io alternatvly (Maybe use skopeo)
  wait-images-to-build-on-quay:
    needs: sync-release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for x min
        run: sleep 1
  # 3. Update the notebook controllers’ image tags on release branch (PR needed to do the final tests)
  update-release-images:
    needs: wait-images-to-build-on-quay
    uses: atheo89/kubeflow/.github/workflows/notebook-controller-images-updater.yaml@main
    with: 
      branch-name: "v1.9t"
      organization: "atheo89"
      generate-pr: "true"
  # 4. Check PR merged status
  check-pr-merged:
    needs: update-release-images
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if the PR is merged
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define the PR title to look for
          PR_TITLE="[GHA-${{ github.run_id }}]"
  
          # Fetch matching PRs and save JSON
          gh pr list --repo atheo89/kubeflow --state all --search "$PR_TITLE" --json number,title > pr_list.json
          
          # Inspect the output
          echo "PR list output:"
          cat pr_list.json
  
          # Extract the PR number
          PR_NUMBER=$(jq '.[0].number' pr_list.json)
          echo "Found PR number: $PR_NUMBER"
  
          if [ -z "$PR_NUMBER" ]; then
            echo "No matching PR found."
            echo "pr_merged=false" >> $GITHUB_ENV
          else
            # Check if the PR is merged
            PR_STATE=$(gh pr view --repo atheo89/kubeflow $PR_NUMBER --json mergedAt --jq '.mergedAt')
            if [ "$PR_STATE" = "null" ]; then
              echo "PR #$PR_NUMBER is not merged yet."
              echo "pr_merged=false" >> $GITHUB_ENV
            else
              echo "PR #$PR_NUMBER is merged."
              echo "pr_merged=true" >> $GITHUB_ENV
            fi
          fi
    outputs:
      pr_merged: ${{ steps.check.outputs.pr_merged }}

  # 5. Create the release
  create-release:
    needs: [update-release-images, check-pr-merged]
    if: needs.check-pr-merged.outputs.pr_merged == 'true'
    uses: atheo89/kubeflow/.github/workflows/hello.yaml@main
    with:
      input_var: "Geia"
