---
# Aim of the action
name: Update Notebook Controller Images With Latest Commit ID
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Provide name of the branch, ex: v1.7-branch"
        required: true

env:
  TEMP_UPDATER_BRANCH: temp-${{ github.run_id }}
  BRANCH_NAME: ${{ github.event.inputs.branch-name || 'v1.7-branch'}}

jobs:
  update-commit-id:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH_NAME }}

    - name: Configure Git
      run: |
       git config --global user.email "github-actions[bot]@users.noreply.github.com"
       git config --global user.name "GitHub Actions"

    - name: Checkout new branch to commit changes
      run: |
       echo ${{ env.TEMP_UPDATER_BRANCH }}
       git checkout -b ${{ env.TEMP_UPDATER_BRANCH }}
       git push --set-upstream origin ${{ env.TEMP_UPDATER_BRANCH }}

    - name: Retrive latest commit
      id: commit-id
      shell: bash
      run: |
        PAYLOAD=$(curl --silent -H 'Accept: application/vnd.github.v4.raw' https://api.github.com/repos/opendatahub-io/kubeflow/commits?sha=$BRANCH_NAME&per_page=1)
        echo "COMMIT_ID=$(echo $PAYLOAD | jq -r '.[0].sha[0:7]')" >> ${GITHUB_OUTPUT}
        echo "COMMIT_ID=$COMMIT_ID"

    - name: Update related files with latest commit ID
      id: apply-changes
      run: |
        COMMIT_ID=${{ steps.commit-id.outputs.COMMIT_ID }}
        echo "COMMIT_ID=${{ steps.commit-id.outputs.COMMIT_ID }}"
        sed -i "s/\(odh-kf-notebook-controller-image=quay\.io\/opendatahub\/kubeflow-notebook-controller:1\.7-\)[a-z0-9]\{7\}/\1$COMMIT_ID/" components/notebook-controller/config/overlays/openshift/params.env
        sed -i "s/\(odh-notebook-controller-image=quay\.io\/opendatahub\/odh-notebook-controller:1\.7-\)[a-z0-9]\{7\}/\1$COMMIT_ID/" components/odh-notebook-controller/config/base/params.env
        sed -i "s/\(KF_TAG ?= 1\.7-\)[a-z0-9]\{7\}/\1$COMMIT_ID/" components/odh-notebook-controller/Makefile

        if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
          git fetch origin  ${{ env.TEMP_UPDATER_BRANCH }} && \
          git pull origin  ${{ env.TEMP_UPDATER_BRANCH }} && \
          git add . && \
          git commit -m "Update odh and notebook-controller with image 1.7-$COMMIT_ID" && \
          git push origin  ${{ env.TEMP_UPDATER_BRANCH }}
        else
            echo "There were no changes detected on ${{ env.BRANCH_NAME }}"
        fi

    - name: Create pull request
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.TEMP_UPDATER_BRANCH }}
        base: ${{ env.BRANCH_NAME }}
        title: "[GHA] Update odh and notebook-controller with image 1.7-${{ steps.commit-id.outputs.COMMIT_ID }}"
        body: |
          :robot: This is an automated Pull Request created by `/.github/workflows/notebook-controller-images-updater.yaml`.

          Have been updated the following related files:
            - components/notebook-controller/config/overlays/openshift/params.env
            - components/odh-notebook-controller/config/base/params.env
            - components/odh-notebook-controller/Makefile
        labels: |
            automated pr
