---
name: Sync Branches

on:
  workflow_dispatch:
    inputs:
      source:
        description: "From:"
        required: true
        type: string
      target:
        description: "To:"
        required: true
        type: string

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensure full history is fetched for merging

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        - name: Merge source branch into target with conflict resolution
      id: merge
      run: |
        set -e
        SOURCE_BRANCH="${{ github.event.inputs.source }}"
        TARGET_BRANCH="${{ github.event.inputs.target }}"

        git fetch origin ${TARGET_BRANCH}:${TARGET_BRANCH}
        git checkout ${TARGET_BRANCH}

        git fetch origin ${SOURCE_BRANCH}:${SOURCE_BRANCH}
        git merge --no-commit origin/${SOURCE_BRANCH} || true

        # Resolve conflicts for specific files
        FILES=(
          "components/notebook-controller/config/overlays/openshift/params.env"
          "components/odh-notebook-controller/config/base/params.env"
        )

        for FILE in "${FILES[@]}"; do
          if [[ -f "$FILE" && "$(git status --porcelain=v1 2>/dev/null | grep -c "$FILE")" -gt 0 ]]; then
            echo "Resolving conflict for $FILE by keeping target branch version."
            git checkout --ours "$FILE"
            git add "$FILE"
          fi
        done

        # Handle the Makefile
        MAKEFILE="components/odh-notebook-controller/Makefile"
        if [[ -f "$MAKEFILE" && "$(git status --porcelain=v1 2>/dev/null | grep -c "$MAKEFILE")" -gt 0 ]]; then
          echo "Resolving conflicts in $MAKEFILE while preserving KF_TAG."

          # Extract conflicting version of the Makefile
          git checkout --theirs "$MAKEFILE" -m

          # Extract the KF_TAG line from the target branch
          KF_TAG_TARGET=$(git show :2:"$MAKEFILE" | grep '^KF_TAG \?=' || echo "")

          # Construct a new Makefile while ignoring changes to KF_TAG
          awk -v kf_tag="$KF_TAG_TARGET" '
            /^KF_TAG \?=/ { print kf_tag; next } # Replace KF_TAG line with target branch version
            { print $0 }                        # Print all other lines
          ' "$MAKEFILE" > "$MAKEFILE.new"

          # Replace original Makefile with updated version
          mv "$MAKEFILE.new" "$MAKEFILE"

          # Stage the updated Makefile
          git add "$MAKEFILE"
        fi

        # Commit the merge changes
        git commit -m "Merge ${SOURCE_BRANCH} into ${TARGET_BRANCH} with resolved conflicts, preserving KF_TAG in Makefile" || echo "Nothing to commit"

        # Create a new branch for the sync
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        SYNC_BRANCH="sync__${SOURCE_BRANCH}__${TARGET_BRANCH}__${TIMESTAMP}"
        git checkout -b $SYNC_BRANCH
        git push origin $SYNC_BRANCH
        echo "branch=$SYNC_BRANCH" >> $GITHUB_OUTPUT


    - name: Create a Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        SOURCE_BRANCH="${{ github.event.inputs.source }}"
        TARGET_BRANCH="${{ github.event.inputs.target }}"
        SYNC_BRANCH=$(echo "${{ steps.merge.outputs.branch }}")
        gh pr create \
          --title "Sync ${SOURCE_BRANCH} into ${TARGET_BRANCH}" \
          --body ":robot: This is an automated PR generated by `/.github/workflows/sync-branches-through-pr.yaml`" \
          --base "${{ github.event.inputs.target }}" \
          --head "${SYNC_BRANCH}"
