name: Sync Branches

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      source:
        description: Source branch
        required: true
      target:
        description: Target branch
        required: true

jobs:
  sync:
    name: Sync branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch target branch
        run: |
          git fetch origin ${{ github.event.inputs.target }}:${{ github.event.inputs.target }}

      - name: Create temporary branch for changes
        run: |
          git checkout ${{ github.event.inputs.target }}
          git checkout -b sync-${{ github.event.inputs.source }}-to-${{ github.event.inputs.target }}
          git merge --no-commit --no-ff ${{ github.event.inputs.source }} || true

      - name: Resolve conflicts
        run: |
          # Explicitly resolve conflicts for the specified files
          echo "Resolving conflict in components/notebook-controller/config/overlays/openshift/params.env"
          echo "odh-kf-notebook-controller-image=quay.io/opendatahub/kubeflow-notebook-controller:1.9-adf190d" > components/notebook-controller/config/overlays/openshift/params.env

          echo "Resolving conflict in components/odh-notebook-controller/Makefile"
          echo "KF_TAG ?= 1.9-adf190d" > components/odh-notebook-controller/Makefile

          echo "Resolving conflict in components/odh-notebook-controller/config/base/params.env"
          echo "odh-notebook-controller-image=quay.io/opendatahub/odh-notebook-controller:1.9-adf190d" > components/odh-notebook-controller/config/base/params.env
          
          # Mark the files as resolved
          git add components/notebook-controller/config/overlays/openshift/params.env
          git add components/odh-notebook-controller/Makefile
          git add components/odh-notebook-controller/config/base/params.env
          
          # Continue the merge
          git commit -m "Resolve conflicts for syncing ${{ github.event.inputs.source }} into ${{ github.event.inputs.target }}" || echo "No changes to commit"

      - name: Push changes to a new branch
        run: |
          git push origin sync-${{ github.event.inputs.source }}-to-${{ github.event.inputs.target }} --force

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: sync-${{ github.event.inputs.source }}-to-${{ github.event.inputs.target }}
          base: ${{ github.event.inputs.target }}
          title: "Sync ${{ github.event.inputs.source }} into ${{ github.event.inputs.target }}"
          body: |
            This pull request syncs the `${{ github.event.inputs.source }}` branch into the `${{ github.event.inputs.target }}` branch.
            Conflicts were resolved in the following files:
            - `components/notebook-controller/config/overlays/openshift/params.env`
            - `components/odh-notebook-controller/Makefile`
            - `components/odh-notebook-controller/config/base/params.env`
          draft: false
