name: Sync branches through Pull Request

on:
  workflow_dispatch:
    inputs:
      source:
        description: Source branch
        required: true
      target:
        description: Target branch
        required: true

jobs:
  sync:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch source branch
        run: git fetch origin ${{ github.event.inputs.source }}

      - name: Merge source branch into target
        id: merge
        run: |
          set -e
          git merge --no-commit origin/${{ github.event.inputs.source }} || true
          # Resolve conflicts for the specific files
          FILES=(
            "components/notebook-controller/config/overlays/openshift/params.env"
            "components/odh-notebook-controller/Makefile"
            "components/odh-notebook-controller/config/base/params.env"
          )

          for FILE in "${FILES[@]}"; do
            if [[ -f "$FILE" && "$(git status --porcelain=v1 2>/dev/null | grep -c "$FILE")" -gt 0 ]]; then
              echo "Resolving conflict for $FILE by keeping target branch version."
              git checkout --ours "$FILE"
              git add "$FILE"
            fi
          done

          # Commit merge changes
          git commit -m "Merge ${github.event.inputs.source} into ${github.event.inputs.target} with resolved conflicts" || echo "Nothing to commit"

          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          SYNC_BRANCH=sync__${{ github.event.inputs.source }}__${{ github.event.inputs.target }}__${TIMESTAMP}
          echo "branch=$SYNC_BRANCH" >> $GITHUB_OUTPUT
          git checkout -b $SYNC_BRANCH
          git push origin $SYNC_BRANCH

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          branch: ${{ steps.merge.outputs.branch }}
          title: "Sync `${{ github.event.inputs.target }}` branch with `${{ github.event.inputs.source }}` branch"
          body: |
            :robot: This is an automated Pull Request created by `/.github/workflows/sync-branches-through-pr.yml`.

            It merges all commits from `${{ github.event.inputs.source }}` branch into `${{ github.event.inputs.target }}` branch.

            :warning: **IMPORTANT NOTE**: Remember to delete the `${{ steps.merge.outputs.branch }}` branch after merging the changes.
