---
name: Sync branches through Pull Request

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      source:
        description: Source branch
        required: true
      target:
        description: Target branch
        required: true

jobs:
  sync:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target }}
          fetch-depth: 0

      - name: Prepare sync branch
        id: prepare
        run: |
          git fetch origin ${{ github.event.inputs.source }}
          git reset --hard origin/${{ github.event.inputs.source }}

          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          SYNC_BRANCH=sync__${{ github.event.inputs.source }}__${{ github.event.inputs.target }}__${TIMESTAMP}
          echo "branch=$SYNC_BRANCH" >> $GITHUB_OUTPUT

      - name: Merge target branch into source branch, handle conflicts
        run: |
          git checkout -b ${{ steps.prepare.outputs.branch }} origin/${{ github.event.inputs.target }}
          git merge --no-commit origin/${{ github.event.inputs.source }} || true

          # Define the line pattern to preserve in the target branch
          LINE_PATTERN1="odh-notebook-controller-image=quay.io/opendatahub/odh-notebook-controller:1.9-*" 
          LINE_PATTERN2="odh-kf-notebook-controller-image=quay.io/opendatahub/kubeflow-notebook-controller:1.9-**"
          LINE_PATTERN3="KF_TAG ?= 1.9-**"


          #components/odh-notebook-controller/Makefile
          #components/odh-notebook-controller/config/base/params.env


          # Resolve conflict by keeping the target branch's version for the specified line
          TARGET_LINE1=$(grep "$LINE_PATTERN1" components/notebook-controller/config/overlays/openshift/params.env) ||  true
          if [ -n "$TARGET_LINE1" ]; then
            # Use target branch's line
            sed -i "s|$LINE_PATTERN1|$TARGET_LINE1|" components/notebook-controller/config/overlays/openshift/params.env
          fi
          git add components/notebook-controller/config/overlays/openshift/params.env

          # Resolve conflict by keeping the target branch's version for the specified line
          TARGET_LINE2=$(grep "$LINE_PATTERN2" components/odh-notebook-controller/config/base/params.env) ||  true
          if [ -n "$TARGET_LINE2" ]; then
            # Use target branch's line
            sed -i "s|$LINE_PATTERN2|$TARGET_LINE2|"  components/odh-notebook-controller/config/base/params.env
          fi
          git add components/notebook-controller/config/overlays/openshift/params.env

            # Resolve conflict by keeping the target branch's version for the specified line
          TARGET_LINE3=$(grep "$LINE_PATTERN3" components/odh-notebook-controller/Makefile) ||  true
          if [ -n "$TARGET_LINE3" ]; then
            # Use target branch's line
            sed -i "s|$LINE_PATTERN3|$TARGET_LINE3|" components/odh-notebook-controller/Makefile
          fi
          git add components/odh-notebook-controller/Makefile

          # Commit the merge, resolving conflicts
          git commit -m "Merge ${{ github.event.inputs.source }} into ${{ github.event.inputs.target }} resolve conflicts"

      - name: Create pull request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f  # v7.0.5
        with:
          branch: ${{ steps.prepare.outputs.branch }}
          title: "Sync `${{ github.event.inputs.target }}` branch with `${{ github.event.inputs.source }}` branch"
          body: |
            :robot: This is an automated Pull Request created by `/.github/workflows/sync-branches-through-pr.yml`.

            It merges all commits from `${{ github.event.inputs.source }}` branch into `${{ github.event.inputs.target }}` branch.

            :warning: **IMPORTANT NOTE**: Remember to delete the `${{ steps.prepare.outputs.branch }}` branch after merging the changes.
